# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Evan Swihart
title: Recent College Graduate (BSCS)
email: swidude@gmail.com
website: https://evan-swihart.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  Evan-Swihart
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: evanswihart1
linkedin_username: evan-swihart1
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: "@veebsCS"
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile2.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Evan and I'm a recent college graduate looking for a job in the tech industry. I have worked a lot with C++ and Java, but I am also familiar with Python, HTML, CSS, and JavaScript. Currently, I am working on making a few different small games like snake or tetris in a few languages, such as python, JavaScript (which I plan to embed here), Java, and C#.

  I am most skilled in: <mark>C++</mark>, <mark>Java</mark> and <mark>Playing Guitar Mediocrely</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Python Snake
        link: github.com/Evan-Swihart
        link_text: My GitHub Page
        additional_links:
        - title:  Snake Repository
          icon: fab fa-github
          url: https://github.com/Evan-Swihart/pysnake/
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Snake without a grid, and that's about it
        description: | # this will include new lines to allow paragraphs
          The game is currently about 90% of the way to completion, and the things that need to be completed are listed as issues in the repository. One of those issues is actually documentation for the project, which I find ironic. I plan to finish the project by the end of the week, and then will move on to a javascript game I can embed right above this text blurb.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Diablo Escapes
        link: diabloescapes.com
        # link_text: boringcompany.com
        sub_title: Summer Intern
        caption: Summer 2022
        quote: >
          Ever experienced a 50-foot dragon fly overhead? I haven't either, but I have seen a *simulated* 50-foot dragon fly over my head and shot a crossbow at it.
        description: | # this will include new lines to allow paragraphs
          I worked at Diablo Escapes as an Intern where I configured a network of multiple VR machines and PCs to facilitate a seamless wireless VR escape room experience, ensuring that all required programs were set to launch automatically upon startup. Additionally, I diagnosed and resolved issues with malfunctioning PC and VR hardware components, restoring full functionality. Throughout, I comprehensively documentated the step-by-step setup and troubleshooting procedures, designed to assist future team members with limited familiarity of PC and VR systems.
          
          I was also in charge of making sure neither the dragon nor the interns ate each other.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Miami University
        caption: 2019 - 2023
        sub_title: BS Computer Science
        quote: >
          Established in 1809, Miami University "bears the name of the Myaamia people", and retains a relationship with the Miami Tribe of Okhlahoma. Miami is a top 50 public university according to U.S. News and World Report, and the number two ranked university for undergraduate engineering.
        description: | # this will include new lines to allow paragraphs
          During my time at Miami I learnt many of my key skills that have I will continue to use through my career such as teamwork and problem solving. I tried to maintain a school life balance, and succeeded for the most part. I did well in all of my classes while still having time to participate in my preffered clubs and activities.

          I spent a lot of my free time as an active member of the *League of Geeks*, which had many sub clubs I participated in such as the *Strategy Gaming Club* or the *Esports Club*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Basketball
      - Music
      - Gaming
      - Rock Climbing

      I also love dragons, so here's a picture of one: 

      ![Dragon!](/images/dragon.png "Dragon")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
